services:
  flightlog:
    build: .
    volumes:
      - flightlog_data:/data
    ports:
      - "44313:44313"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:44313
      - SqliteConnectionString=Data Source=/data/flightlog.db;Cache=Shared

volumes:
  flightlog_data: